name: tracking-server

on:
  push:
    branches: [ "master" ]

jobs:
  tracking-setup:
    name: tracking-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up environment variables
        run: |
          echo "POSTGRES_USER=${{ vars.POSTGRES_USER }}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
          echo "MINIO_ROOT_USER=${{ vars.MINIO_ROOT_USER }}" >> $GITHUB_ENV
          echo "MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}" >> $GITHUB_ENV
          echo "MINIO_DEFAULT_BUCKETS=${{ vars.MINIO_DEFAULT_BUCKETS }}" >> $GITHUB_ENV
          echo "EXPERIMENT_TRACKER_PATH=${{ vars.EXPERIMENT_TRACKER_PATH }}" >> $GITHUB_ENV
          echo "GIT_URL=${{ vars.GIT_URL }}" >> $GITHUB_ENV

      - name: SSH into server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_DB,MINIO_ROOT_USER,MINIO_ROOT_PASSWORD,MINIO_DEFAULT_BUCKETS,EXPERIMENT_TRACKER_PATH,GIT_URL
          script: |
            if [[ -d "${EXPERIMENT_TRACKER_PATH}" ]]; then 
              cd $EXPERIMENT_TRACKER_PATH
              git pull origin master
            else
              git clone $GIT_URL $EXPERIMENT_TRACKER_PATH
              cd $EXPERIMENT_TRACKER_PATH
            fi

            echo "POSTGRES_USER=$POSTGRES_USER" >> .env
            echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
            echo "POSTGRES_DB=$POSTGRES_DB" >> .env
            echo "MINIO_ROOT_USER=$MINIO_ROOT_USER" >> .env
            echo "MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD" >> .env
            echo "MINIO_DEFAULT_BUCKETS=$MINIO_DEFAULT_BUCKETS" >> .env
            
            docker compose up -d